### ISSUE TITLE
Bug in Safari for the CSS Step animation

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#60]
The CSS animation has a bug in Safari where it appears that the step distance is off somehow:

![safari-animation-bug](https://user-images.githubusercontent.com/1256329/57117291-12eb2d80-6d29-11e9-80ed-bbd939f2cea8.gif)

This appears to only be happening in Safari. I wasn't able to reproduce the issue in Chrome, Firefox, or Edge.

**Comment by tigt** [comment]
Looks like it’s a different value provided in the prefixed keyframes:

```css
@-webkit-keyframes bounce {
  from { background-position: 0px;     }
  to   { background-position: -2850px; }
}
```

Instead of the `-3762px` the unprefixed version has.

It should be safe to stop using the prefix, since CanIUse reports only 0.04% gain in browser support with them.
